"""initial schema

Revision ID: 31a1936add10
Revises: 
Create Date: 2026-07-17 15:03:29.681987

"""
from alembic import op
import sqlalchemy as sa
import app.models


revision = '31a1936add10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('domain', sa.String(length=24), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', app.models.UUIDBin(length=16), nullable=False),
    sa.Column('handle', sa.String(length=32), nullable=False),
    sa.Column('birth_year', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('cortex_index',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', app.models.UUIDBin(length=16), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cortex_index_user_at', 'cortex_index', ['user_id', 'computed_at'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', app.models.UUIDBin(length=16), nullable=False),
    sa.Column('user_id', app.models.UUIDBin(length=16), nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('spec_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('issued', 'valid', 'rejected', 'quarantined', 'void', name='session_status'), nullable=False),
    sa.Column('server_metrics', sa.JSON(), nullable=True),
    sa.Column('device', sa.JSON(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_user_game_submitted', 'game_sessions', ['user_id', 'game_id', 'submitted_at'], unique=False)
    op.create_table('rating_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', app.models.UUIDBin(length=16), nullable=False),
    sa.Column('domain', sa.String(length=24), nullable=False),
    sa.Column('rating', sa.Double(), nullable=False),
    sa.Column('rd', sa.Double(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rating_history_user_domain_at', 'rating_history', ['user_id', 'domain', 'at'], unique=False)
    op.create_table('skill_ratings',
    sa.Column('user_id', app.models.UUIDBin(length=16), nullable=False),
    sa.Column('domain', sa.String(length=24), nullable=False),
    sa.Column('rating', sa.Double(), nullable=False),
    sa.Column('rd', sa.Double(), nullable=False),
    sa.Column('volatility', sa.Double(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'domain')
    )
    op.create_table('user_game_state',
    sa.Column('user_id', app.models.UUIDBin(length=16), nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    op.create_table('trials',
    sa.Column('session_id', app.models.UUIDBin(length=16), nullable=False),
    sa.Column('trial_index', sa.SmallInteger(), nullable=False),
    sa.Column('onset_ms', sa.Double(), nullable=False),
    sa.Column('response_ms', sa.Double(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('false_start', sa.Boolean(), nullable=False),
    sa.Column('interrupted', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'trial_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trials')
    op.drop_table('user_game_state')
    op.drop_table('skill_ratings')
    op.drop_index('ix_rating_history_user_domain_at', table_name='rating_history')
    op.drop_table('rating_history')
    op.drop_index('ix_sessions_user_game_submitted', table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index('ix_cortex_index_user_at', table_name='cortex_index')
    op.drop_table('cortex_index')
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
